#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

cat ami.stl rotor_fillet_05.stl > domain.stl

runApplication surfaceFeatureEdges domain.stl domain.fms -angle 30

runApplication cartesianMesh

touch zzz.foam

runApplication checkMesh -constant -allGeometry -allTopology -writeAllFields -writeSets vtk

#------------------------------------------------------------------------------
