#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

cat inlet.stl outlet.stl sides.stl > domain.stl

runApplication surfaceFeatureEdges domain.stl domain.fms

runApplication cartesianMesh

touch zzz.foam

runApplication checkMesh -constant -allGeometry -allTopology -writeAllFields -writeSets vtk

#------------------------------------------------------------------------------
