#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

cp -r ../rotating_mesh/constant/polyMesh constant/

rm -rf constant/polyMesh/meshMetaDict constant/polyMesh/sets

runApplication mergeMeshes ./ ../stationary_mesh/ -overwrite

runApplication renumberMesh -overwrite

touch zzz.foam

runApplication checkMesh -constant

runApplication topoSet

restore0Dir

runApplication setFields

runApplication moveDynamicMesh -noFunctionObjects

# decomposePar

# mpirun -np 32 overPimpleDyMFoam -parallel

#------------------------------------------------------------------------------
